basePath: /
definitions:
  dto.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  dto.HistoryResponse:
    properties:
      apr:
        type: number
      created_at:
        type: string
      link:
        type: string
      operation:
        type: string
      provider:
        type: string
      token:
        type: string
    type: object
  dto.LiquidityPoolHistoryResponse:
    properties:
      apr:
        type: number
      created_at:
        type: string
      link:
        type: string
      provider:
        type: string
      token_a:
        type: string
      token_b:
        type: string
    type: object
host: api.lovelyglam.life
info:
  contact: {}
  description: This is the API documentation for Zenick Aggregator.
  title: Zenick Aggregator API
  version: "1.0"
paths:
  /histories:
    get:
      consumes:
      - application/json
      description: Retrieve detailed history records with related entities
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.HistoryResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get detailed histories
      tags:
      - Histories
  /histories/GetHistoriesByCondition:
    get:
      consumes:
      - application/json
      description: Retrieve histories based on filter conditions
      parameters:
      - description: Provider name
        in: query
        name: provider
        type: string
      - description: Token name
        in: query
        name: token
        type: string
      - description: Operation name
        in: query
        name: operation
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.HistoryResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get histories by condition
      tags:
      - Histories
  /histories/GetHistoryByCondition:
    get:
      consumes:
      - application/json
      description: Retrieve history based on filter conditions
      parameters:
      - description: Provider name
        in: query
        name: provider
        type: string
      - description: Token name
        in: query
        name: token
        type: string
      - description: Operation name
        in: query
        name: operation
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.HistoryResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get history by condition
      tags:
      - Histories
  /liquidityPoolHistories:
    get:
      consumes:
      - application/json
      description: Retrieve detailed liquidityPoolHistory records with related entities
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.LiquidityPoolHistoryResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get detailed liquidityPoolHistories
      tags:
      - LiquidityPoolHistories
  /liquidityPoolHistories/GetLiquidityPoolHistoryByCondition:
    get:
      consumes:
      - application/json
      description: Retrieve Liquidity Pool History based on filter conditions
      parameters:
      - description: Provider name
        in: query
        name: provider
        type: string
      - description: Token A name
        in: query
        name: token_a
        type: string
      - description: Token B name
        in: query
        name: token_b
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LiquidityPoolHistoryResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get Liquidity Pool History by condition
      tags:
      - LiquidityPoolHistories
swagger: "2.0"
