on:
  push:
    branches:
      - main
    paths:
      - server/**
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      GIT_REGISTRY: ghcr.io/${{ github.repository }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Convert REGISTRY to lowercase
        run: echo "REGISTRY=$(echo $GIT_REGISTRY | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Build and push Docker image
        run: |
          docker compose -f compose.build.yaml build --parallel
          docker compose -f compose.build.yaml push
  web-deploy:
    runs-on: self-hosted
    needs: build-image
    env:
      GIT_REGISTRY: ghcr.io/${{ github.repository }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      ROOT_DOMAIN: ${{ secrets.ROOT_DOMAIN }}
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3
      - name: Convert REGISTRY to lowercase
        run: echo "REGISTRY=$(echo $GIT_REGISTRY | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean Container, Image And Prepare For Deploy
        run: docker compose -f compose.yaml -p zenick-application pull

      - name: Infisical Login && Deploy Client
        run: docker compose -f compose.yaml -p zenick-application up -d

      - name: Prune Docker System
        run: docker system prune -af
