name: crawl
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  fetch-chapter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          targets: x86_64-unknown-linux-gnu
          toolchain: nightly

      - name: Cache Rust dependencies and build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            crawler/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run
        working-directory: ./crawler
        shell: bash
        run: |
          cargo run
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
